- pkg/framework/simulator.go
- vendor/k8s.io/kubernetes/pkg/admission/chain.go
- vendor/k8s.io/kubernetes/pkg/admission/plugins.go
- vendor/k8s.io/kubernetes/plugin/pkg/admission/admit/admission.go
- vendor/k8s.io/kubernetes/plugin/pkg/admission/alwayspullimages/admission.go
- vendor/k8s.io/kubernetes/plugin/pkg/admission/antiaffinity/admission.go
- vendor/k8s.io/kubernetes/plugin/pkg/admission/deny/admission.go
- vendor/k8s.io/kubernetes/plugin/pkg/admission/exec/admission.go
- vendor/k8s.io/kubernetes/plugin/pkg/admission/gc/gc_admission.go
- vendor/k8s.io/kubernetes/plugin/pkg/admission/imagepolicy/admission.go
- vendor/k8s.io/kubernetes/plugin/pkg/admission/initialresources/admission.go
- vendor/k8s.io/kubernetes/plugin/pkg/admission/limitranger/admission.go
- vendor/k8s.io/kubernetes/plugin/pkg/admission/namespace/autoprovision/admission.go
- vendor/k8s.io/kubernetes/plugin/pkg/admission/namespace/exists/admission.go
- vendor/k8s.io/kubernetes/plugin/pkg/admission/namespace/lifecycle/admission.go
- vendor/k8s.io/kubernetes/plugin/pkg/admission/persistentvolume/label/admission.go
- vendor/k8s.io/kubernetes/plugin/pkg/admission/podnodeselector/admission.go
- vendor/k8s.io/kubernetes/plugin/pkg/admission/resourcequota/admission.go
- vendor/k8s.io/kubernetes/plugin/pkg/admission/security/podsecuritypolicy/admission.go
- vendor/k8s.io/kubernetes/plugin/pkg/admission/securitycontext/scdeny/admission.go
- vendor/k8s.io/kubernetes/plugin/pkg/admission/serviceaccount/admission.go
- vendor/k8s.io/kubernetes/plugin/pkg/admission/storageclass/default/admission.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/controller.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/fifo.go
This is needed to eliminate handing go-routines.
> Apply go routines prs

- cmd/cluster-capacity/app/options/options.go
- cmd/cluster-capacity/app/server.go
- cmd/genpod/app/options/options.go
- cmd/genpod/app/server.go
- pkg/utils/utils.go
Issue: https://github.com/kubernetes-incubator/cluster-capacity/issues/33
> Load current master address from kubeconfig file

- cmd/cluster-capacity/app/options/options.go
- cmd/cluster-capacity/app/server.go
- cmd/genpod/app/server.go
- pkg/apiserver/handler.go
- pkg/apiserver/watch.go
- pkg/client/nspod.go
- pkg/framework/report.go
- pkg/framework/restclient/restclient.go
- pkg/framework/restclient/restclient_test.go
- pkg/framework/restclient/watch_test.go
- pkg/framework/simulator.go
- pkg/framework/simulator_test.go
- pkg/framework/store/fake.go
- pkg/framework/store/store.go
- pkg/framework/strategy/strategy.go
- pkg/framework/strategy/strategy_test.go
- pkg/framework/watch/watch.go
- pkg/utils/utils.go
Minor string fixes and a code simplification for configuration of admission control plugin names.
> Minor code cleanups

- integration-tests.sh
- pkg/utils/utils.go
SSIA
Extends #38 
DO NOT MERGE YET
> fix retrieval of master url from kubeconfig

- cmd/cluster-capacity/app/server.go
- pkg/apiserver/cache/cache.go
- pkg/apiserver/handler.go
- pkg/apiserver/watch.go
- pkg/apiserver/watch_test.go
- pkg/framework/report.go
- pkg/framework/simulator.go
- pkg/framework/simulator_test.go
+ prepare ClusterCapacityReview to scheduling pod sequences
Issue: https://github.com/kubernetes-incubator/cluster-capacity/issues/15
> Rename Report to ClusterCapacityReview and refactor 

- integration-tests.sh
- verify/boilerplate/boilerplate.py
- verify/verify-boilerplate.sh
1) fixing path in the boilerplate from repo-infra ro cluster-capacity
2) running the boilerplate verification as part of the integration tests
> Fix path to cc boilerplate

- README.md
It removed `--master` option from Readme as the option has been removed.
> Fix readme to remove --master option.

- .travis.yml
- test.sh
> add travis CI

- .travis.yml
> extend travis with make build

- cmd/cluster-capacity/app/options/options.go
- cmd/cluster-capacity/app/server.go
- config/apiserver.yaml
- integration-tests.sh
- pkg/framework/simulator.go
- pkg/framework/simulator_test.go
- set built-in values for authorization config
- add flag admission-control for specifying admission plugins
> Remove command option - ApiServerOption

- cmd/cluster-capacity/app/server.go
- pkg/framework/report.go
- remove maps
- prepare for structure moving to another package
- pod resources as resourceList
> ClusterCapacityReview - minor fixups

- README.md
> Fix README to reflect the current state.

- cmd/cluster-capacity/app/server.go
- cmd/cluster-capacity/main.go
- cmd/genpod/main.go
- cmd/hypercc/main.go
> Fix exit error codes and a misspelled flag.

- cmd/hypercc/hypercc.go
- cmd/hypercc/main.go
> Implement hypercc as a super command of cluster capacity commands.

- pkg/framework/simulator.go
for now, mock stateful sets input to the scheduler.
> Mock StatefulSets for scheduler

- cmd/cluster-capacity/app/options/options.go
- pkg/framework/restclient/external/restclient.go
- pkg/framework/restclient/external/restclient_test.go
- pkg/framework/watch/watch.go
- pkg/utils/utils.go
@derekwaynecarr 
Fix https://github.com/kubernetes-incubator/cluster-capacity/issues/70
> Fix testapi and default scheduler config

- pkg/framework/simulator.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1449891
@derekwaynecarr
> Fix cluster-capacity to avoid pending pods not created by it.

- README.md
@aveshagarwal these are updates from the work yesterday with running CC as a job.
> updated README with details on how to run Cluster Capacity as a job

- Dockerfile
- cmd/cluster-capacity/app/options/options.go
- cmd/cluster-capacity/app/server.go
- pkg/utils/utils.go
It broke after rebase to 1.9. Also did some minor changes to Dockerfile.
> Fix cluster-capacity functionality as a pod.

- README.md
> Be clear about building steps

- SECURITY_CONTACTS
Fix https://github.com/kubernetes-incubator/cluster-capacity/issues/98
> Add SECURITY_CONTACTS file.

- pkg/framework/strategy/strategy.go
Fix typos: asuming -> assuming
> Fix typos: asuming -> assuming

- .travis.yml
- Makefile
- README.md
- cmd/cluster-capacity/app/server.go
- cmd/cluster-capacity/main.go
- cmd/genpod/app/server.go
- cmd/genpod/main.go
- cmd/hypercc/hypercc.go
- cmd/hypercc/main.go
- doc/RUN_IN_KUBERNETES.md
- doc/html/home.html
- pkg/framework/simulator.go
- test.sh
Repo got moved from kubernetes-incubator to kubernetes-sigs org.
> Rename path prefix to sigs.k8s.io

- OWNERS
> Remove folks no longer participating and add dameni

- .travis.yml
- cmd/cluster-capacity/app/server.go
- hack/boilerplate/boilerplate.generatego.txt
- hack/lib/golang.sh
- hack/lib/init.sh
- hack/lib/logging.sh
- hack/lib/util.sh
- hack/unit-test.sh
- hack/update-gofmt.sh
- hack/verify-gofmt.sh
- pkg/framework/report.go
- pkg/framework/simulator_test.go
- pkg/framework/strategy/strategy_test.go
- pkg/test/util.go
Toward switching to Prow through https://github.com/kubernetes/test-infra/pull/17686
> Add make verify gofmt target

- cmd/cluster-capacity/app/server.go
> Propagate klog flags

- Makefile
- test/e2e/e2e_test.go
- test/run-e2e-tests.sh
> Introduce e2e tests

- hack/kind_config.yaml
- test/run-e2e-tests.sh
Creating cluster "kind" ...
ERROR: failed to create cluster: error reading file: open ./hack/kind_config.yaml: no such file or directory
> Add missing hack/kind_config.yaml

- .travis.yml
> Drop deprecated .travis.yml

- Gopkg.lock
- Gopkg.toml
- vendor/k8s.io/apiserver/pkg/server/options/authentication.go
- vendor/k8s.io/apiserver/pkg/server/options/authorization.go
- vendor/k8s.io/apiserver/pkg/server/options/recommended.go
- vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
- vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook/webhook.go
- vendor/k8s.io/apiserver/plugin/pkg/authorizer/webhook/webhook.go
- vendor/k8s.io/cloud-provider/go.mod
- vendor/k8s.io/cloud-provider/go.sum
- vendor/k8s.io/csi-translation-lib/go.mod
- vendor/k8s.io/csi-translation-lib/go.sum
- vendor/k8s.io/csi-translation-lib/plugins/aws_ebs.go
- vendor/k8s.io/csi-translation-lib/plugins/azure_file.go
- vendor/k8s.io/csi-translation-lib/plugins/openstack_cinder.go
https://github.com/kubernetes/kubernetes/releases/tag/v1.20.5
> Bump kubernetes to 1.20.5

- pkg/framework/simulator.go
The fake clientset does not properly handle field selectors in informers. Thus, filter out succeeded and failed pods explicitly.
> filter out succeeded and failed pods when populating pods

- .gitignore
This isn't exactly urgent, but it's definitely pretty annoying.
> Ignore builds

- Dockerfile
- Makefile
- cloudbuild.yaml
- cmd/cluster-capacity/app/server.go
- examples/pod-with-no-resource-limits.yaml
- pkg/version/version.go
- pkg/version/version_test.go
Following steps in https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md#cloudbuildyaml and duplicating the config from https://github.com/kubernetes-sigs/descheduler.
> feat: enabled automatic builds
