kubernetes-sigs/cluster-capacity

- Makefile
- integration-tests.sh
- test.sh
Basically just an entry point for CI. ``make integration-tests`` expects Kubernetes cluster deployed. The following set of envs should be set accordingly:
* KUBE_MASTER_API
* KUBE_MASTER_API_PORT
* KUBE_CONFIG
For time being, the integration tests can be run once a Kubernetes cluster is deployed via vagrant [1]. Something like this:
```sh
$ vagrant up
$ vagrant ssh-config
$ sudo echo "IP kube-master-1"
$ sudo scp -i ~/.vagrant.d/insecure_private_key vagrant@kube-master-1:/etc/kubernetes/kubectl.kubeconfig .
$ export KUBE_MASTER_API=https://kube-master-1
$ export KUBE_MASTER_API_PORT=[6]443
$ export KUBE_CONFIG=kubectl.kubeconfig
$ make integration-tests
```
[1] https://github.com/kubernetes/contrib/tree/master/ansible/vagrant
> Introduce first integration tests

- pkg/framework/report.go
Fixes https://github.com/kubernetes-incubator/cluster-capacity/issues/39
I think we should look to use color more if/when upstream sets precedence for colors.
> Remove colors

- integration-tests.sh
api and port are detected from kubeconfig now
> remove api and port env from integration tests

- pkg/framework/report.go
It was due to incorrectly reading cpu values for both memory and nvidiagpu. The output looked as follows:
```
small-pod pod requirements:
- CPU: 150m
- Memory: 104857600150m
```
And after fix, the output is restored:
```
small-pod pod requirements:
- CPU: 150m
- Memory: 100Mi
```
> Fix broken output of pod requirements for memory and nvidiagpu.

- cmd/genpod/app/options/options.go
- cmd/genpod/app/server.go
As master is directly read from kubeconfig, there is no need to keep master field as part of genpodoptions.
> Remove master from genpodoptions.

- pkg/framework/report.go
- pkg/framework/simulator.go
This gets rid of the extraneous logging of the error when a fit is no longer possible.
> Simulator should not log errors when there is no fit

- pkg/api/api.go
- pkg/framework/restclient/external/restclient.go
- pkg/framework/simulator.go
- pkg/framework/simulator_test.go
- pkg/framework/store/store.go
the cluster-capacity command should work with same RBAC privileges as scheduler - bind.
remove resources not needed by the scheduler framework from being pulled.
> cluster-capacity should only list resources needed by scheduler

- pkg/api/api.go
- pkg/client/nspod.go
- pkg/framework/restclient/external/restclient.go
- pkg/framework/restclient/external/restclient_test.go
- pkg/framework/restclient/external/watch_test.go
- pkg/framework/simulator.go
- pkg/framework/store/fake.go
- pkg/framework/store/store.go
- pkg/framework/watch/watch.go
@derekwaynecarr 
I have reduced resource further to only pods and nodes. With this and RBAC, the only role that is needed to run cluster capacity is:
```
kind: ClusterRole
apiVersion: v1
metadata:
name: cc-role
rules:
- apiGroups: [""]
resources: ["pods", "nodes",  "persistentvolumeclaims", "persistentvolumes", "services"]
verbs: ["get", "watch", "list"]
```
> Remove resources that are not needed to run cluster capacity analysis.

- .travis.yml
Travis CI is configured for Go 1.7.  It needs to use 1.8.
> travis ci should use go 1.8

- integration-tests.sh
Remove BASH function definition syntax in integration-tests.sh to be able to run it in a system with a different default shell (e.g. ubuntu).
> Make functions in integration-test.sh script POSIX compliant.

- Makefile
- cmd/cluster-capacity/app/options/options.go
- cmd/cluster-capacity/app/server.go
Also if the input pod to cluster capacity
does not specify its scheduler name, set the name to cluster-capacity too.
> Set cluster capacity's scheduler instance's name to cluster-capacity to avoid  conflict with default-scheduler. 

- doc/api-definitions.md
The table FailReasons format is wrong.
need to insert a empty line below "##FailReasons"
> Correct the format of table in api-definitions.md

- cmd/cluster-capacity/app/server.go
If not set, the following panic occurs:
```
./cluster-capacity --kubeconfig ~/.kube/config  --podspec examples/pod.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x16daa79]
goroutine 1 [running]:
sigs.k8s.io/cluster-capacity/vendor/k8s.io/component-base/logs.(*Options).Get(...)
/go/src/sigs.k8s.io/cluster-capacity/cmd/hypercc/main.go:42 +0x2f
```
> Initialize kube-scheduler's logs options

- test/run-e2e-tests.sh
To test the binary works over the default example without a panic.
See https://github.com/kubernetes-sigs/cluster-capacity/pull/127.
> test-e2e: just run the binary with the default example

- doc/cluster-capacity.md
I found there are 2 words that I can't tell. But I supposed these words are what they are.
> Fix typo of cluster-capacity doc

- Makefile
- hack/unit-test.sh
- test/run-e2e-tests.sh
The project still imports code from kubernetes/kubernetes repository
which is go module less.
https://golang.org/doc/go1.16#go-command
> Set GO111MODULE=auto to build cc with go1.16

- pkg/framework/simulator.go
The fake clientset does not properly handle field selectors in informers. Thus, filter out succeeded and failed pods explicitly.
> filter out succeeded and failed pods when populating pods

- pkg/framework/simulator.go
An internal case user has reached the maximum channel size intermittently and with this PR I am increasing it considerably to avoid that. 
```
cluster-capacity --kubeconfig kd --podspec md --verbose
panic: channel full
goroutine 1 [running]:
k8s.io/apimachinery/pkg/watch.(*RaceFreeFakeWatcher).Add(0xc001d9d680?, {0x2217f40?, 0xc001d9db00?})
/go/src/sigs.k8s.io/cluster-capacity/vendor/k8s.io/apimachinery/pkg/watch/watch.go:218 +0x153
k8s.io/client-go/testing.(*tracker).add(0xc000181810, {{0x1f20fd5, 0x4}, {0x1f2044f, 0x2}, {0x1f2a706, 0xb}}, {0x2217f40, 0xc001d9cd80}, {0xc000e313f8, ...}, ...)
/go/src/sigs.k8s.io/cluster-capacity/vendor/k8s.io/client-go/testing/fixture.go:431 +0xded
k8s.io/client-go/testing.(*tracker).Create(0xc000181810?, {{0x1f20fd5, 0x4}, {0x1f2044f, 0x2}, {0x1f2a706, …
```
> Increase channel size

- Dockerfile
Original syntax will result in:
```bash
$ make image
docker build -t cluster-capacity .
Sending build context to Docker daemon  161.9MB
Step 1/6 : FROM golang:latest
...
Successfully built dae542bae31f
Successfully tagged cluster-capacity:latest
$ docker run --rm cluster-capacity:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/bin/cluster-capacity --help": stat /bin/cluster-capacity --help: no such file or directory: unknown.
```
> fix: Dockerfile CMD syntax

- test/run-e2e-tests.sh
To address:
```
+ kind load docker-image registry.k8s.io/pause
Image: "registry.k8s.io/pause" with ID "sha256:350b164e7ae1dcddeffadd65c76226c9b6dc5553f5179153fb0e36b78f2a5e06" not yet present on node "kind-worker", loading...
Image: "registry.k8s.io/pause" with ID "sha256:350b164e7ae1dcddeffadd65c76226c9b6dc5553f5179153fb0e36b78f2a5e06" not yet present on node "kind-worker2", loading...
Image: "registry.k8s.io/pause" with ID "sha256:350b164e7ae1dcddeffadd65c76226c9b6dc5553f5179153fb0e36b78f2a5e06" not yet present on node "kind-control-plane", loading...
ERROR: failed to detect containerd snapshotter
```
> e2e: bump kind to v0.27.0
